### ISSUE TITLE
Consumer stop consuming after an error related to broker rebalance

### ISSUE THREAD

**Issue by phunguyen19** [uizaio/node-kafka-client#6]
During use this library, we something having some Broker errors like: `Error: Broker: Unknown member`, `Error: Broker: Not coordinator for group`, `Error: Broker: Rebalancing in progress`, ...

The root cause is about we are using `commitMessageSync` function. If the consumer try to commit during the Broker rebalance the group, it will occur the error.

The solution is using `commitMessage` instead as the issue have been discover and fixed in the issue https://github.com/edenhill/librdkafka/issues/1605

**Comment by onimsha** [comment]
This issue can be close now
