### ISSUE TITLE
Issue when committing message in the flowing mode

### ISSUE THREAD

**Issue by quachduyy** [uizaio/node-kafka-client#8]
In case we have the number of consumers less than the number of partitions, there is a problem in the `flowingCommitQueue` logic [here](https://github.com/uizaio/node-kafka-client/blob/master/lib/consumer.js#L171) since the condition only compare the message offset. 

Actually, if your consumer has to consume multiple partitions, this condition will not valid because of the duplicated offset between the partitions.

**Comment by phunguyen19** [comment]
@quachduyy @onimsha I have made a PR to fix this bug. Please help check.
